import { Member, WordPair, S2JStory } from './types';

export const membersData: Member[] = [
  // OWNER
  {
    id: 'owner-anom',
    username: 'S2JxAa_anom',
    role: 'owner',
    avatarSeed: 'anom',
    status: 'online',
    statusText: 'Ngaping dulur-dulur kabeh 🙏✨',
    origin: 'Sunda',
    joinedDate: 'Agustus 2024',
    customIcon: '👑',
    colorTheme: 'from-orange-500 to-red-600',
  },
  // ADMINS
  {
    id: 'admin-zee',
    username: 'S2JxZeeChei',
    role: 'admin',
    avatarSeed: 'zee',
    status: 'online',
    statusText: 'Rukun agawe santosa 🤝',
    origin: 'Jawa',
    joinedDate: 'September 2024',
    customIcon: '👑',
    colorTheme: 'from-purple-500 to-violet-600',
  },
  {
    id: 'admin-aca',
    username: 'S2JxAcaaa',
    role: 'admin',
    avatarSeed: 'aca',
    status: 'online',
    statusText: 'Silih asih, silih asah, silih asuh 🌻',
    origin: 'Sunda',
    joinedDate: 'September 2024',
    customIcon: '🌻',
    colorTheme: 'from-fuchsia-500 to-indigo-600',
  },
  {
    id: 'admin-cheisy',
    username: 'S2JxCheisyZee',
    role: 'admin',
    avatarSeed: 'cheisy',
    status: 'idle',
    statusText: 'Ngopi santai bersama keluarga 🌸',
    origin: 'Jawa',
    joinedDate: 'Oktober 2024',
    customIcon: '🌸',
    colorTheme: 'from-pink-500 to-purple-600',
  },
  // MEMBERS
  {
    id: 'mem-kem',
    username: 'S2J x Mr.Kem®',
    role: 'member',
    avatarSeed: 'kem',
    status: 'online',
    statusText: 'Gas lur, no rasis club! ⚡',
    origin: 'Nusantara',
    joinedDate: 'Desember 2024',
    colorTheme: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'mem-afif',
    username: 'S2JxAFIFBAIK 💀1312',
    role: 'member',
    avatarSeed: 'afif',
    status: 'offline',
    statusText: 'Solidaritas nomor siji.',
    origin: 'Jawa',
    joinedDate: 'Januari 2025',
    colorTheme: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'mem-cipi',
    username: 'S2JxCipiwwww',
    role: 'member',
    avatarSeed: 'cipi',
    status: 'online',
    statusText: 'Someah ka sadayana, asoyy 🍃',
    origin: 'Sunda',
    joinedDate: 'Februari 2025',
    colorTheme: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'mem-gula',
    username: 'S2JxGulaAren',
    role: 'member',
    avatarSeed: 'gula',
    status: 'online',
    statusText: 'Manis koyo rasaning dulur 🍯',
    origin: 'Jawa',
    joinedDate: 'Februari 2025',
    colorTheme: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'mem-kyotaka',
    username: 'S2JxKyotaka ⚡ONIC',
    role: 'member',
    avatarSeed: 'kyotaka',
    status: 'online',
    statusText: 'Fokus mabar dulur-dulur 🎮',
    origin: 'Nusantara',
    joinedDate: 'Maret 2025',
    colorTheme: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'mem-mosh',
    username: 'S2JxMosshhhh',
    role: 'member',
    avatarSeed: 'mosh',
    status: 'idle',
    statusText: 'Nikmati alam Jawa & Sunda 🏔️',
    origin: 'Sunda',
    joinedDate: 'April 2025',
    colorTheme: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'mem-tyya',
    username: 'SJ2xTyya',
    role: 'member',
    avatarSeed: 'tyya',
    status: 'online',
    statusText: 'Damai neng kene baraya 💕',
    origin: 'Jawa',
    joinedDate: 'Mei 2025',
    colorTheme: 'from-emerald-500 to-teal-600',
  },
];

export const s2jKamus: WordPair[] = [
  {
    indonesia: 'Selamat Datang',
    sunda: 'Wilujeng Sumping',
    jawa: 'Sugeng Rawuh',
    context: 'Ucapan menyambut tamu atau saudara baru.',
  },
  {
    indonesia: 'Persaudaraan',
    sunda: 'Kabarayaan / Kasaduluran',
    jawa: 'Seduluran',
    context: 'Ikatan kekeluargaan yang erat dan suci.',
  },
  {
    indonesia: 'Terima Kasih',
    sunda: 'Hatur Nuhun',
    jawa: 'Matur Nuwun',
    context: 'Ungkapan rasa hormat dan terima kasih.',
  },
  {
    indonesia: 'Ramah dan Sopan',
    sunda: 'Someah',
    jawa: 'Grahak / Andhap Ashor',
    context: 'Karakter utama masyarakat Sunda dan Jawa.',
  },
  {
    indonesia: 'Bersama-sama',
    sunda: 'Sasarengan',
    jawa: 'Bareng-bareng / Bebarengan',
    context: 'Kebersamaan dan gotong royong.',
  },
  {
    indonesia: 'Apa Kabar',
    sunda: 'Kumaha Damang?',
    jawa: 'Pripun Kabare? / Piye Kabare?',
    context: 'Menanyakan kabar dengan penuh kepedulian.',
  },
  {
    indonesia: 'Damai / Rukun',
    sunda: 'Rukun / Harmonis',
    jawa: 'Tentrem / Adem Ayem',
    context: 'Menjaga harmoni dalam kehidupan sehari-hari.',
  },
  {
    indonesia: 'Saya / Aku',
    sunda: 'Abdi / Kuring',
    jawa: 'Kulo / Aku',
    context: 'Penyebutan diri yang santun.',
  },
  {
    indonesia: 'Bicara Baik / Sopan',
    sunda: 'Nyarios Sae',
    jawa: 'Matom / Rembagan Alus',
    context: 'Prinsip komunikasi yang damai.',
  },
];

export const initialStories: S2JStory[] = [
  {
    id: 'story-1',
    sender: 'S2JxAa_anom',
    role: 'owner',
    origin: 'Sunda',
    message: 'Wilujeng sumping di platform S2J! Ieu wadah kasaduluran urang sarerea. Hayu urang silih kadek, silih asih, silih asuh pikeun karukunan Sunda sareng Jawa selawase. Damai salawasna! 🙌💛',
    timestamp: '2 jam yang lalu',
    likes: 24,
  },
  {
    id: 'story-2',
    sender: 'S2JxZeeChei',
    role: 'admin',
    origin: 'Jawa',
    message: 'Sugeng rawuh sedulurku kabeh! S2J kuwi omah kanggo awake dewe sing dadi keluarga modern. Pancen rukun kuwi agawe santosa, ayo sinergi bebarengan njogo kehormatan S2J. Salam seduluran selawase! 👑✨',
    timestamp: '3 jam yang lalu',
    likes: 18,
  },
  {
    id: 'story-3',
    sender: 'S2JxAcaaa',
    role: 'admin',
    origin: 'Sunda',
    message: 'Abdi reueus pisan dinten ieu kumpul sareng dulur Jawa sareng Sunda. Di S2J urang silih rangkul tur silih hormat, teu aya bedana asal daerah. Rukun tur someah salawasna ya gess! 🌸🍃',
    timestamp: '5 jam yang lalu',
    likes: 15,
  },
  {
    id: 'story-4',
    sender: 'S2J x Mr.Kem®',
    role: 'member',
    origin: 'Nusantara',
    message: 'Absen malam baraya! Seneng banget bisa nemu tempat nongkrong se-adem ayem gini. Mari terus rawat persaudaraan sejati ini tanpa batas. Salam hangat buat semuanya! ☕🔥',
    timestamp: '8 jam yang lalu',
    likes: 12,
  },
];

export const s2jVoices = [
  { id: 'v-1', name: '🔊 Obrolan Santuy (Sunda-Jawa)', activeUsers: ['S2JxAa_anom', 'S2JxZeeChei', 'S2JxGulaAren'], type: 'general' },
  { id: 'v-2', name: '🎤 Pojok Karokean Degung & Gamelan', activeUsers: ['S2JxCheisyZee', 'S2JxCipiwwww'], type: 'music' },
  { id: 'v-3', name: '⛺ Curhat Antar Dulur', activeUsers: ['S2JxAcaaa', 'SJ2xTyya', 'S2JxMosshhhh'], type: 'chit-chat' },
];

export const galleryItems = [
  {
    id: 'gal-1',
    title: 'Indahnya Parahyangan',
    subtitle: 'Pegunungan Jawa Barat',
    category: 'Sunda',
    imageUrl: 'https://images.unsplash.com/photo-1594918731557-0b154807466d?auto=format&fit=crop&w=800&q=80',
    description: 'Hamparan perkebunan teh hijau di dataran tinggi Jawa Barat yang melambangkan kesegaran, keindahan alam, dan kedamaian hati baraya Sunda.',
  },
  {
    id: 'gal-2',
    title: 'Megahnya Borobudur',
    subtitle: 'Karya Agung Nusantara',
    category: 'Jawa',
    imageUrl: 'https://images.unsplash.com/photo-1584810359583-96fc3448beaa?auto=format&fit=crop&w=800&q=80',
    description: 'Simbol kebijaksanaan luhur, ketenangan spiritual, dan kerajinan agung yang terpahat indah di bumi Jawa untuk dunia.',
  },
  {
    id: 'gal-3',
    title: 'Gamelan & Angklung Berpadu',
    subtitle: 'Sinergi Harmoni Musik Tradisional',
    category: 'Kolaborasi',
    imageUrl: 'https://images.unsplash.com/photo-1534156039819-c89418369a4f?auto=format&fit=crop&w=800&q=80',
    description: 'Ketika getaran bambu yang ceria menyatu dengan gema perunggu yang sakral dalam aransemen musik modern digital.',
  },
  {
    id: 'gal-4',
    title: 'Batik Sawat & Megamendung',
    subtitle: 'Estetika Motif Adiluhung',
    category: 'Sajak Motif',
    imageUrl: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=800&q=80',
    description: 'Hiasan garuda agung bersanding mesra dengan rupa awan yang meneduhi. Karya seni sakral warisan Nusantara sejati.',
  },
  {
    id: 'gal-5',
    title: 'Kehangatan Secangkir Wedang & Kopi',
    subtitle: 'Rasa yang Menyatukan Kita',
    category: 'Ruang Santai',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    description: 'Tak peduli secangkir kopi murni priangan maupun segelas wedang jahe manis lereng Lawu, semua berseru dalam semangat kekeluargaan.',
  },
  {
    id: 'gal-6',
    title: 'Gunungan & Pagelaran Wayang',
    subtitle: 'Filosofi Alur Kehidupan',
    category: 'Jawa',
    imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=800&q=80',
    description: 'Gunungan melambangkan alam semesta, gejolak hati manusia, rintangan mendaki, serta persatuan puncak ketakwaan kepada Sang Pencipta.',
  }
];
